### ISSUE TITLE
[BUG] Some PINS are not compatible with the profile

### ISSUE THREAD

**Issue by crashzk** [ianlucas/cs2-inventory-simulator#1]
I believe you already know, but we have some PINS that it is not possible to equip in the player's profile in the inventory option.

![image](https://github.com/ianlucas/cs2-inventory-simulator/assets/32937653/eb20ac6e-c2b8-4111-b018-4babd249e414)

These operations pins can be removed from the list.

**Comment by ianlucas** [comment]
This should be resolved now.  For technical details, see below.

https://github.com/ianlucas/cslib/blob/995d85f071beac4c258871195e2bf94b004da634/scripts/generate.ts#L572

Let me know if you find any other issue related to this.

Thanks,
Ian.
