### ISSUE TITLE
[REQ] Implement Storage Unit Tool

### ISSUE THREAD

**Issue by crashzk** [ianlucas/cs2-inventory-simulator#10]
Would it be possible to implement a feature to save items in the storage unit?

![image](https://github.com/ianlucas/cs2-inventory-simulator/assets/32937653/9b7efc9c-77e0-474c-b72f-29ee92934012)

**Comment by ianlucas** [comment]
I'm starting to think how to tackle this. By default we have an inventory limit of 256 items. If we allow users to store items inside Storage Units that would mean allow more items to be stored, I'm thinking in allowing up to 32 items inside it initially (that would mean up to 7936 (255 * 32) items could be stored in total).

This probably won't create a performance issue, but I'll need to test.
