### ISSUE TITLE
[REQ] Inventory is full informational message

### ISSUE THREAD

**Issue by crashzk** [ianlucas/cs2-inventory-simulator#100]
A user reported that he is no longer getting craft skins, there is no option for him.

![image](https://github.com/user-attachments/assets/cfb81243-3ad5-4fcb-be12-ae19b36f1093)

I did the test myself, and everything was fine for me, the option shows normally.

![image](https://github.com/user-attachments/assets/f2d9e13f-361f-4043-9b18-50ea24f0efac)

What could cause this, would it be a limit on skins in the inventory?

If so, is there any way to leave a message for the user when they reach the skin limit? Leave the option but whenever he clicks to create new items it will show a warning.

**Comment by ianlucas** [comment]
Yeah, he probably has reached the inventory item limit.

**Comment by ianlucas** [comment]
Now "Craft" will always by shown in the header, but it will be disabled if the user's inventory is full. They can sneak into `/craft` page, but they will get a sync error if try to create a new item.
