### ISSUE TITLE
[REQ/RULE] Rule to change user inventory and storage limit

### ISSUE THREAD

**Issue by crashzk** [ianlucas/cs2-inventory-simulator#101]
It would be possible to add two rules, one so that we can change the user's inventory limit and the other rule to increase the limit of skins in their storage.

In other words, the default that is configured in the database remains for everyone, but if I added these two rules for the user, it would have a new limit and only that.

Or would this feature already be possible?

**Comment by ianlucas** [comment]
Already possible using `inventoryMaxItems` rule and `public."UserRule"` table.
