### ISSUE TITLE
[REQ] Display specials only for unlocked item when opening cases

### ISSUE THREAD

**Issue by KewaiiGamer** [ianlucas/cs2-inventory-simulator#111]
When a case is opened if a yellow item shows up while spinning it should land on it always. 

On CS2 the behaviour is there is no yellow item showing up unless it''s going to land on it

**Comment by ianlucas** [comment]
I'm pretty sure I've seen special items being skipped when case opening, but I wasn't able to find a footage of it.  Do you have any other source supporting this behavior?

**Comment by KewaiiGamer** [comment]
Well. I can ask one of my players to record next time they open cases. but it has happend over 20 times on like 600 cases openings.

**Comment by ianlucas** [comment]
I'm actually referring to CS2 itself, in Inventory Simulator I'm sure this is happening as we don't filter out special items unlocks from the dummy unlocks.

**Comment by KewaiiGamer** [comment]
had a lot of players saying that should be the case but indeed I can't confirm it by searching online either and I never opened a single case and don't watch videos of youtubers. Best method is find video proof of some youtuber opening cases and whether this happens.
