### ISSUE TITLE
[REQ/RULE] Share link

### ISSUE THREAD

**Issue by crashzk** [ianlucas/cs2-inventory-simulator#113]
Rule so that we can control who has access to the option to share skins.

I also noticed that the share option only shows on skins, would this really be the behavior?

![image](https://github.com/user-attachments/assets/13a22471-8eff-43e9-96a8-4fc4a6c46e79)

Or should I show everyone the inventory?

**Comment by ianlucas** [comment]
It's the intended behavior, the idea is to share crafts. Stickers, cases, etc. are consumer items, so they are easily craftable.
