### ISSUE TITLE
[REQ] Improvements to the Wear & Seed selection system

### ISSUE THREAD

**Issue by crashzk** [ianlucas/cs2-inventory-simulator#12]
Would it be possible to implement the option for the user to enter the Wear and Seed they would like to put on?

Leave the one you currently have, but the fields are editable.
![image](https://github.com/ianlucas/cs2-inventory-simulator/assets/32937653/b66eee56-f808-4905-a139-7eab262beaeb)

**Comment by crashzk** [comment]
I noticed that the quantity system cannot be typed either, it would be interesting to include this feature where you can type it too.

![image](https://github.com/ianlucas/cs2-inventory-simulator/assets/32937653/4fa0cfdd-c5b7-4970-bac8-c0356e31355c)

**Comment by ianlucas** [comment]
Suggestion noted.

**Comment by ianlucas** [comment]
Addressed on eb044a209cada3933ca72fcc05f7a904571bc1f1
