### ISSUE TITLE
StatTrak incrementing issue

### ISSUE THREAD

**Issue by kubo997** [ianlucas/cs2-inventory-simulator#121]
There is an issue with StatTrak incrementation when using a PostgreSQL database. This error does not occur when using MySQL.

**Comment by ianlucas** [comment]
Okay, can you be more specific (logs, error message)? The project currently only supports PostgresSQL, not sure how MySQL would work instead of it.

**Comment by ianlucas** [comment]
Closing this for now. Let me now once you have more information about this. It is working as expected on my instance.
