### ISSUE TITLE
[REQ] Support changing background

### ISSUE THREAD

**Issue by crashzk** [ianlucas/cs2-inventory-simulator#13]
Would it be possible to implement support so that we can change the background?

Something like CS2, map background option and such.
![image](https://github.com/ianlucas/cs2-inventory-simulator/assets/32937653/6db06979-dc22-43f4-94ee-e6e875cbcde1)

It would also not be possible for the **Settings** option to move as if it were an option when clicking on our nickname or profile photo.

In this case, this change only stops when he is logged in, if he is not logged in with Steam it remains as it is currently.

**Comment by crashzk** [comment]
@ianlucas new backgrounds were added in CS2, could you add them to the project too?

**Comment by ianlucas** [comment]
> @ianlucas new backgrounds were added in CS2, could you add them to the project too?

Hopefully soon.
