### ISSUE TITLE
[BUG] Item description with errors

### ISSUE THREAD

**Issue by crashzk** [ianlucas/cs2-inventory-simulator#134]
![image](https://github.com/user-attachments/assets/d35c566c-08cc-4734-98fe-d65e33de0e15)

Could this "error in the name" be something in the game?

**Comment by ianlucas** [comment]
It's from the game.

![image](https://github.com/user-attachments/assets/494e7f0a-909e-46b6-8fdc-8c6cdf69cf1c)

![image](https://github.com/user-attachments/assets/aae0dc47-f469-458d-b466-917df2fef8e5)
