### ISSUE TITLE
[BUG] Apply Sticker to C4

### ISSUE THREAD

**Issue by crashzk** [ianlucas/cs2-inventory-simulator#14]
![image](https://github.com/ianlucas/cs2-inventory-simulator/assets/32937653/baddc037-4404-4816-872f-855586ca2ec6)

Can we expect in future updates to see the sticker on the weapon like in CS2 and as it is removed, it will also update on the skin until it is completely removed?

I believe this is the same issue addressed in Issues #6.

**Comment by crashzk** [comment]
One note, C4 has the option to apply/remove stickers on it, CS2 itself has no way to do this.

C4 even only allows applying Nametag in this case.

**Comment by ianlucas** [comment]
Yeah, this is totally related to #6, I'm going to use this issue to fix the bug with the C4 allowing stickers.
