### ISSUE TITLE
[REQ] Shanghai QF Trophy

### ISSUE THREAD

**Issue by crashzk** [ianlucas/cs2-inventory-simulator#143]
![image](https://github.com/user-attachments/assets/dd58b778-4127-4bf5-b05f-8f323052d443)

I believe it is absent, or this edition did not have this trophy like in previous ones?

**Comment by ianlucas** [comment]
As far as I know, Valve has not yet given the collectives to the players, until they hand them over it won't be available. (Source: [magixx's inventory](https://steamcommunity.com/id/getboris/inventory))
