### ISSUE TITLE
[REQ] Change in the option to add users to groups

### ISSUE THREAD

**Issue by crashzk** [ianlucas/cs2-inventory-simulator#149]
I've recently been developing a plugin to communicate with inventory simulator. It works simply. Players who are VIPs and buy VIPs will receive the `VIP` group on the site and will be added to their position.

However, I noticed that if I try to add a `userId` that is not in the database, it generates an error and the user is not added.

![image](https://github.com/user-attachments/assets/4ab7f29b-4297-4a93-a750-0fea4f195f05)

The error occurred as I mentioned because this user has never even logged into the site. Would it be possible to change this? Even if he has never logged into the site, I can add his `userId` and when he connects, he will have access to all VIP privileges on the site;

**Comment by ianlucas** [comment]
The database enforces that the user must exist before associating them to a group. So first your plugin logic will need to check if the user exists, if they don't exist in the database:

1. Do nothing. (I recommend this approach)
2. OR create a user in `User` (user information will be updated as soon they sign in to the website), and then associate them to the group.
