### ISSUE TITLE
[REQ] Option to enable/disable features in the web panel

### ISSUE THREAD

**Issue by crashzk** [ianlucas/cs2-inventory-simulator#19]
I believe that in the future we can use this web interface as the basis for a [CSSharp](https://docs.cssharp.dev/) plugin for CS2.

Use it so we can change the player's inventory within the server. This left a question, can we have a root/admin access option that allows us to enable and disable features in the web panel?

For example, it allows players to use the panel but they will not have access to open capsules, cases, acquire keys, etc. Just leave the option to choose skins, change nametag, stattrak and stickers.

Could something like this be possible for the future?

**Comment by ianlucas** [comment]
Yes, that's planned. I'll be using this issue to keep its progress.

**Comment by ianlucas** [comment]
Please let me know everything you think would be useful to be configurable.

**Comment by crashzk** [comment]
At first I believe that all categories for creating items have the option to enable or disable them.
![image](https://github.com/ianlucas/cs2-inventory-simulator/assets/32937653/72588cc4-ba50-423f-8d39-7702e0ce60e4)

Example, Tool, Key & Containers options leave disabled;

I believe that in theory it would be the entire project, let's say. Because in the future I'm thinking about implementing features so that the user can open boxes on the web panel and get the drop skin on the server too.

Case/skin drop system within the server that makes the server earn the skin on the panel as well.

Anyway, millions of ideas, but due to the limitations of CS2 and CSSharp we still can't do it.

**Comment by crashzk** [comment]
It would also be interesting to have a way to activate/deactivate the option to **Edit** a craft we made.

![image](https://github.com/ianlucas/cs2-inventory-simulator/assets/32937653/2eebebd7-ee0e-41f9-a004-15f8ab925b06)

**Comment by ianlucas** [comment]
This is now implemented. There will be no administrative interface on CS2 Inventory Simulator, this configuration must be done in the database (or any other interface that modifies it).

For any future request, use [REQ/RULE] prefix.
