### ISSUE TITLE
[Q] Support for installation via Easypanel

### ISSUE THREAD

**Issue by crashzk** [ianlucas/cs2-inventory-simulator#20]
Any support for installing via the [Easypanel](https://easypanel.io/) panel?

**Comment by ianlucas** [comment]
No support will be given to deployment, but it should be straightforward by following the [deployment instructions](https://github.com/ianlucas/cs2-inventory-simulator#deployment).

**Comment by crashzk** [comment]
I understand, I just started with Node.js applications, in this case I even got a VPS for just that.

The question that remained for me is, where should I send these files, which folder, etc., so that I can then start it. `root` folder or other...

Anyway, when researching easypanel I saw that it would be the simplest, in any case I will be researching more on how to run applications directly from the command line, where to send project files, etc.
