### ISSUE TITLE
[Q] Stats for nerds

### ISSUE THREAD

**Issue by crashzk** [ianlucas/cs2-inventory-simulator#21]
What would stats for nerds be?

![image](https://github.com/ianlucas/cs2-inventory-simulator/assets/32937653/a1fd10bf-0e92-42e0-90b2-fbc575f91dab)

I already left it activated/deactivated and I still don't understand...

**Comment by ianlucas** [comment]
Currently it's used just to display the current sticker wear when scraping a sticker.
