### ISSUE TITLE
[BUG] Steam auth not working

### ISSUE THREAD

**Issue by johandrevwyk** [ianlucas/cs2-inventory-simulator#26]
I forked the repo and deployed it using EasyPanel while changing to MySQL, database seems to load fine, my api key is correct in environment variables. When I auth, it redirects back, but its not signed in. No errors are displayed

**Comment by ianlucas** [comment]
Can you provide me the pathname you're using for your `STEAM_CALLBACK_URL`? It should be `/sign-in/steam/callback`.

**Comment by ianlucas** [comment]
Just tested a fresh clone of the repo with the following `.env` file without issues. Please check your setup.

```env
# Required environment variables
# DATABASE_URL ~ To use MySQL or other supported DB, you need to update `prisma/schema.prisma`.
DATABASE_URL="postgres://postgres:postgres@localhost:5432/mytestdb?schema=public"
SESSION_SECRET="your session secret"
# Optional environment variables
STEAM_API_KEY="---my steam api key---"
STEAM_CALLBACK_URL="http://localhost:3000/sign-in/steam/callback"
```

**Comment by ianlucas** [comment]
Also worth checking `Rule` table, make sure your Steam API and callback URL are defined there.

**Comment by johandrevwyk** [comment]
Issue was definitely the callback url, it wasnt stated in the env example where it must point to

**Comment by jpf666** [comment]
> Issue was definitely the callback url, it wasnt stated in the env example where it must point to
I have the same problem. I didn't quite understand how you solved it, could you explain it please?

**Comment by jpf666** [comment]
> Issue was definitely the callback url, it wasnt stated in the env example where it must point to

I have the same problem. I didn't quite understand how you solved it, could you explain it please?

**Comment by ianlucas** [comment]
@jpf666 it works as stated in my comments, take a look at table `public.Rule` and check if you have the correct URL for [`steamCallbackUrl`](https://github.com/ianlucas/cs2-inventory-simulator/blob/main/docs/rules.md#steamcallbackurl) there.

**Comment by jpf666** [comment]
![Image](https://github.com/user-attachments/assets/7899510a-7944-40dd-b0c9-331af130d08b)


this way? Thanks in advance for the support

**Comment by ianlucas** [comment]
Yes, like this. But I should point out that you're using MySQL while the project officially only supports Postgres, so it's up to you debug what could be the issue for it to not be working as expected.
