### ISSUE TITLE
[REQ/RULE] Option to enable/disable specific categories

### ISSUE THREAD

**Issue by crashzk** [ianlucas/cs2-inventory-simulator#29]
![image](https://github.com/ianlucas/cs2-inventory-simulator/assets/32937653/9ed119c0-1927-40dd-8d52-856cfb2dcd99)

It would be interesting to have the option to disable if we want some categories, for example, remove the Case, Key, etc. categories from the menu.

Every category has the option to enable/disable them.

**Comment by ianlucas** [comment]
This is already implemented, see [Rules documentation](https://github.com/ianlucas/cs2-inventory-simulator/blob/main/docs/rules.md).
