### ISSUE TITLE
[BUG] Warning message `You are not authenticated...`

### ISSUE THREAD

**Issue by crashzk** [ianlucas/cs2-inventory-simulator#30]
![image](https://github.com/ianlucas/cs2-inventory-simulator/assets/32937653/860f0953-e88b-4cb4-b0f8-4b413db65779)

I noticed that this warning is only displayed to the user if they have already logged in to the site. In other words, if you have never logged in and change your skins, you will not receive this warning, so you will not be notified that you need to be logged in to synchronize your skins.

Wouldn't it be correct for the message to appear to all users, even if they have never logged in to the site?

**Comment by ianlucas** [comment]
That's the intended behavior, if the user for some reason got unauthenticated they are notified they are changing items without reflecting it with the server. Returning users will know they need to authenticate if it's the first time they are accessing the page on the browser.
