### ISSUE TITLE
[REQ] Option to edit Header, Footer & SEO

### ISSUE THREAD

**Issue by crashzk** [ianlucas/cs2-inventory-simulator#31]
Would it be possible to configure/change some Header, Footer & SEO information via the database?

What I thought of was some option to change the logo in the Header.

![image](https://github.com/ianlucas/cs2-inventory-simulator/assets/32937653/7e63feed-1f12-453f-8c3a-e05b7a6f5332)

Option to change the favicon and title of the site, would be interesting.
![image](https://github.com/ianlucas/cs2-inventory-simulator/assets/32937653/0d801c23-87b2-4c2a-a11d-c725d2d8b198)

SEO when we share the link by default with this information, it would be an interesting option to edit this text.

![image](https://github.com/ianlucas/cs2-inventory-simulator/assets/32937653/b23b1138-cacf-4d13-8205-415061853ed1)

Regarding the site's credits, I thought about removing the `Source Code` and leaving the direct link to the project in the name in the credits.
![image](https://github.com/ianlucas/cs2-inventory-simulator/assets/32937653/4e929abe-ca31-4291-afb4-ce833bb381d0)

And in addition to the project credits, you can also put a message at the front that we can change, for example:

[cstrike's Inventory Simulator](https://github.com/ianlucas/cs2-inventory-simulator) - CUSTOMIZABLE MESSAGE

**Comment by ianlucas** [comment]
This will not be supported by the project right now.
