### ISSUE TITLE
[BUG] No items to display for cases

### ISSUE THREAD

**Issue by avcrope** [ianlucas/cs2-inventory-simulator#38]
I really really like your website I've been looking for one for many many while but can you fix stuff including like on some cases it says "No items to display" because when i get some case and it says that i cant  open and and also is it impossible to pull knifes because ive been playing for a couple days and I've never pulled one how can i change the pull rate ands last thing. can you make accounts that have their own data and not just on steam like make a simple account with username password etc. that saves the guns and stuff so you don't have to have many steam accounts to log in with. like i said i really like your website and i would love for it to be further worked on thank you a lot my friend.
![pasted](https://github.com/ianlucas/cs2-inventory-simulator/assets/116221387/d4d4f792-0ae2-4d1e-9cc3-8510dc027576)

**Comment by avcrope** [comment]
Also maybe have a pin feature to pin items to the top and maybe price system and trade? and yes I'm aware that would take lots of time

**Comment by ianlucas** [comment]
Whoa whoa, fist things first - regarding the issue you are reporting: Kilowatt cases require keys, did you craft its keys, too? The app simulates the game, you can't open cases only by adding them to your inventory.

Currently only Steam authentication will be supported, no plans to add another method sorry. And regarding your other suggestions, please open an issue for each suggestion using the [REQ] prefix in the title, detail your request and I'll look over them.
