### ISSUE TITLE
[REQ] More Storage.

### ISSUE THREAD

**Issue by avcrope** [ianlucas/cs2-inventory-simulator#39]
Is it possible to make the storage unit or just the default storage to a higher number so i can put more stuff in a storage unit or in my inventory thanks.

**Comment by avcrope** [comment]
like make the limiy to a storage unit to like 1,000 or somthing if thats possible

**Comment by ianlucas** [comment]
I increased the storage to `48`, for technical reasons I won't increase it more than that right now. You can move and remove items from storage continually so I don't think we need mass deposit/retrieve features as of now.

**Comment by avcrope** [comment]
> I increased the storage to `48`, for technical reasons I won't increase it more than that right now. You can move and remove items from storage continually so I don't think we need mass deposit/retrieve features as of now.

i have a quistion. is there any way I can change it? and also on your other projects whaty does the "plugin" mean? thankyou.

**Comment by avcrope** [comment]
> I increased the storage to `48`, for technical reasons I won't increase it more than that right now. You can move and remove items from storage continually so I don't think we need mass deposit/retrieve features as of now.

And I'm just saying that because the storage unit is very small. because all i can put is 32 items in it and there is no way that number can be raised? because of issues with the website etc. and are you ever going to take down the website? weird question but i am asking because i really enjoy the website and not hope for it to be shut down.

**Comment by ianlucas** [comment]
> > I increased the storage to `48`, for technical reasons I won't increase it more than that right now. You can move and remove items from storage continually so I don't think we need mass deposit/retrieve features as of now.
> 
> i have a quistion. is there any way I can change it? and also on your other projects whaty does the "plugin" mean? thankyou.

It's a plugin for [CounterStrikeSharp](https://docs.cssharp.dev).

**Comment by ianlucas** [comment]
> > I increased the storage to `48`, for technical reasons I won't increase it more than that right now. You can move and remove items from storage continually so I don't think we need mass deposit/retrieve features as of now.
> 
> And I'm just saying that because the storage unit is very small. because all i can put is 32 items in it and there is no way that number can be raised? because of issues with the website etc. and are you ever going to take down the website? weird question but i am asking because i really enjoy the website and not hope for it to be shut down.

Well currently there is no income from the website so I may be take it down in the future, but I'm trying to keep it as long as I can. I'm probably going to add a way to donate for the people that wish to help with its costs. I'm not increasing the total items right now because I'm monitoring the usage of the website's server. That may change in the future.

The source code is available here so if something goes wrong anyone can take it over.

**Comment by avcrope** [comment]
> > > I increased the storage to `48`, for technical reasons I won't increase it more than that right now. You can move and remove items from storage continually so I don't think we need mass deposit/retrieve features as of now.
> > 
> > 
> > And I'm just saying that because the storage unit is very small. because all i can put is 32 items in it and there is no way that number can be raised? because of issues with the website etc. and are you ever going to take down the website? weird question but i am asking because i really enjoy the website and not hope for it to be shut down.
> 
> Well currently there is no income from the website so I may take it down in the future, but I'm trying to keep it as long as I can. I'm probably going to add a way to donate for the people that wish to help with its costs. I'm not increasing the total items right now because I'm monitoring the usage of the website's server. That may change in the future.
> 
> The source code is available here so if something goes wrong anyone can take it over.

If i have the open source is there any tut how i can set it up on a website like if i have the source how do i make it a wbesite?

**Comment by ianlucas** [comment]
> > > > I increased the storage to `48`, for technical reasons I won't increase it more than that right now. You can move and remove items from storage continually so I don't think we need mass deposit/retrieve features as of now.
> > > 
> > > 
> > > And I'm just saying that because the storage unit is very small. because all i can put is 32 items in it and there is no way that number can be raised? because of issues with the website etc. and are you ever going to take down the website? weird question but i am asking because i really enjoy the website and not hope for it to be shut down.
> > 
> > 
> > Well currently there is no income from the website so I may take it down in the future, but I'm trying to keep it as long as I can. I'm probably going to add a way to donate for the people that wish to help with its costs. I'm not increasing the total items right now because I'm monitoring the usage of the website's server. That may change in the future.
> > The source code is available here so if something goes wrong anyone can take it over.
> 
> If i have the open source is there any tut how i can set it up on a website like if i have the source how do i make it a wbesite?

That's up to you figure out.
