### ISSUE TITLE
[REQ] Improve items scrolling

### ISSUE THREAD

**Issue by crashzk** [ianlucas/cs2-inventory-simulator#4]
![image](https://github.com/ianlucas/cs2-inventory-simulator/assets/32937653/b1803a97-c16f-4ccc-9acc-417b1bcb5110)

I click, hold down to move but without success, nothing happens.

**Comment by ianlucas** [comment]
It's not a real scroll, mostly a scroll indicator. The user needs to use the mouse scroll to scroll through the items. I believe most of the users will use the search functionallity so this won't be high priority for now.

**Comment by ianlucas** [comment]
Resolved by debc96217d1b8f9503ac0f13ab84fa1c96c6e372.
