### ISSUE TITLE
[REQ] Any text alowed in wepon name

### ISSUE THREAD

**Issue by avcrope** [ianlucas/cs2-inventory-simulator#40]
![pasted](https://github.com/ianlucas/cs2-inventory-simulator/assets/116221387/ce355aec-1cae-4c12-8e53-6728d6e15857)

Like for Example "<" and ">" arnt alowed in the name and (") isnt. maybe its a code thing that you cant alow those charicters but can you alow any charicter like any languges and symbols?

**Comment by ianlucas** [comment]
There are constraints for Name Tags, you can learn more [here](https://counterstrike.fandom.com/wiki/Name_Tag).

**Comment by ianlucas** [comment]
> > There are constraints for Name Tags, you can learn more [here](https://counterstrike.fandom.com/wiki/Name_Tag).
> 
> Alr thankyou also is it impossibble to get a gold/knife? i have opend many many cases even just know open 100 in a row and got nothing? whats the chances of a knife?

The vanilla app will try to simulate the same odds as in-game, you can see here:
https://github.com/ianlucas/cslib/blob/a16032e479009b8a7e844dd9becdc77179ab2079/src/economy.ts#L517

So yeah, it's as hard as in-game.

**Comment by avcrope** [comment]
> > > There are constraints for Name Tags, you can learn more [here](https://counterstrike.fandom.com/wiki/Name_Tag).
> > 
> > 
> > Alr thankyou also is it impossibble to get a gold/knife? i have opend many many cases even just know open 100 in a row and got nothing? whats the chances of a knife?
> 
> The vanilla app will try to simulate the same odds as in-game, you can see here: https://github.com/ianlucas/cslib/blob/a16032e479009b8a7e844dd9becdc77179ab2079/src/economy.ts#L517
> 
> So yeah, it's as hard as in-game.

why wont you make it easyier? becuase its more realsitic with the odds that are already in the game

**Comment by ianlucas** [comment]
> > > > There are constraints for Name Tags, you can learn more [here](https://counterstrike.fandom.com/wiki/Name_Tag).
> > > 
> > > 
> > > Alr thankyou also is it impossibble to get a gold/knife? i have opend many many cases even just know open 100 in a row and got nothing? whats the chances of a knife?
> > 
> > 
> > The vanilla app will try to simulate the same odds as in-game, you can see here: https://github.com/ianlucas/cslib/blob/a16032e479009b8a7e844dd9becdc77179ab2079/src/economy.ts#L517
> > So yeah, it's as hard as in-game.
> 
> why wont you make it easyier? becuase its more realsitic with the odds that are already in the game

The goal of the project is to simulate the game.

**Comment by avcrope** [comment]
> > > > > There are constraints for Name Tags, you can learn more [here](https://counterstrike.fandom.com/wiki/Name_Tag).
> > > > 
> > > > 
> > > > Alr thankyou also is it impossibble to get a gold/knife? i have opend many many cases even just know open 100 in a row and got nothing? whats the chances of a knife?
> > > 
> > > 
> > > The vanilla app will try to simulate the same odds as in-game, you can see here: https://github.com/ianlucas/cslib/blob/a16032e479009b8a7e844dd9becdc77179ab2079/src/economy.ts#L517
> > > So yeah, it's as hard as in-game.
> > 
> > 
> > why wont you make it easyier? becuase its more realsitic with the odds that are already in the game
> 
> The goal of the project is to simulate the game.

Why dont you host yourwebsite on like infinityfree where its free?

**Comment by crashzk** [comment]
website does not use PHP/HTML needs correct hosting for this and there are no free options for this.

**Comment by avcrope** [comment]
> website does not use PHP/HTML needs correct hosting for this and there are no free options for this.

RIP.  do you know how to host a website with the open source?
