### ISSUE TITLE
[REQ] Inspect Inventory Items (Info Icon Button)

### ISSUE THREAD

**Issue by avcrope** [ianlucas/cs2-inventory-simulator#46]
Are you able to add a info icon on the bottem left etelling the link the wear and such, When you hover ovcer the sticker you can see the wear anc name of sticker. Have thge inspect buttton avvalible for the wepons in a storage unit and The wepon be able to see if its statrak or not.

**Comment by ianlucas** [comment]
1. Inspect won't be available for storage units as hover already displays all the information for the item.
2. Sticker wear will only display by enabling "Stats for Nerds" setting.
3. Sticker name won't be displayed.

**Comment by avcrope** [comment]
> 1. Inspect won't be available for storage units as hover already displays all the information for the item.
> 2. Sticker wear will only display by enabling "Stats for Nerds" setting.
> 3. Sticker name won't be displayed.

on the sticker wear i mean that it just shows the percent on the inspect. i have the stats for nerds turned on its just easier to know the wear of the sticker besides from it just being faded. and the storage unit. i said that because if im in a storage unit i cant edit the gun inspect or anything i have to pull it out of the unit just to inspect it. So inspecting it you can just see on larger scale so if you make decition to pull it out you can just see it. the and the name. just to make it easier to see because if you hover over the sticker it says the wear and name. and what about showing if its stattrack or not?

**Comment by ianlucas** [comment]
Storage units must be used just for storing or retrieving items, no context menu is planned when inspecting its items for now. The remaining of the issue was implemented, but, again, not deployed. Please be patient and tomorrow (BRT) it should be live.

**Comment by avcrope** [comment]
> Storage units must be used just for storing or retrieving items, no context menu is planned when inspecting its items for now. The remaining of the issue was implemented, but, again, not deployed. Please be patient and tomorrow (BRT) it should be live.

Ok thankyou

**Comment by avcrope** [comment]
> Storage units must be used just for storing or retrieving items, no context menu is planned when inspecting its items for now. The remaining of the issue was implemented, but, again, not deployed. Please be patient and tomorrow (BRT) it should be live.

When is this feature being deployed on your website.

**Comment by avcrope** [comment]
> Storage units must be used just for storing or retrieving items, no context menu is planned when inspecting its items for now. The remaining of the issue was implemented, but, again, not deployed. Please be patient and tomorrow (BRT) it should be live.

In the real game there is a inspect feature?
![pasted](https://github.com/ianlucas/cs2-inventory-simulator/assets/116221387/a00c94cf-ecde-4b00-b2a5-61c427de11f9)
That is pistols in a storage unit with inspect

**Comment by avcrope** [comment]
> Storage units must be used just for storing or retrieving items, no context menu is planned when inspecting its items for now. The remaining of the issue was implemented, but, again, not deployed. Please be patient and tomorrow (BRT) it should be live.

Why isnt it live yet?

**Comment by avcrope** [comment]
> I'm still testing some stuff before deploying it, be patient. Had a lot of changes in the last days.

I understand sorry
