### ISSUE TITLE
[REQ] StatTrak Kills Changer

### ISSUE THREAD

**Issue by avcrope** [ianlucas/cs2-inventory-simulator#47]
Able to change the amout of kills on the stattrak wepon
![pasted](https://github.com/ianlucas/cs2-inventory-simulator/assets/116221387/8490143f-b582-4d1c-904b-cf2401cb381a)

**Comment by ianlucas** [comment]
This value can only by changed by API, won't be available for edition in the website.

**Comment by avcrope** [comment]
> This value can only be changed by API, won't be available for edition in the website.

Ok, Thankyou.
