### ISSUE TITLE
[BUG] Duplicate Pins

### ISSUE THREAD

**Issue by crashzk** [ianlucas/cs2-inventory-simulator#5]
![image](https://github.com/ianlucas/cs2-inventory-simulator/assets/32937653/2eb3c801-e26d-42c8-aae2-05a11eb95a44)

Would these duplicate pins be normal? Or it would be possible to remove them, leaving just one.

**Comment by ianlucas** [comment]
Not a bug. Pratically speaking they are the same, but looks like Commodity Pins are for pins bought from the game store, and Collectible Pins are retrieved from their [physicial counterpart](https://pbs.twimg.com/media/FvD37-eX0AcQwnw?format=jpg&name=large).

Initially I filtered them, but I felt they were "different" enought to keep them.

**Comment by crashzk** [comment]
> Not a bug. Pratically speaking they are the same, but looks like Commodity Pins are for pins bought from the game store, and Collectible Pins are retrieved from their [physical counterpart](https://pbs.twimg.com/media/FvD37-eX0AcQwnw?format=jpg&name=large).
> 
> Initially I filtered them, but I felt they were "different" enough to keep them.

I see, I thought about that too... But would there be any way to change their name? In this case, an identification saying that one would be due to a Physical Pin and such? Or in CS2 even they wouldn't have this different name?

**Comment by crashzk** [comment]
Come on, I now see that there is a description that tells what each one is, my lack of attention, sorry.
