### ISSUE TITLE
[BUG] Hide Stickers from Item Editor as per rule

### ISSUE THREAD

**Issue by crashzk** [ianlucas/cs2-inventory-simulator#50]
I have the following configuration in the rules:
```
CraftHideType: patch;case;key;graffiti;tool;sticker;pin;agent;musickit
```
![image](https://github.com/ianlucas/cs2-inventory-simulator/assets/32937653/925bb9c9-a1d1-4876-9fea-20ad20163d68)

So far, everything is fine, as you can see in the screenshot:
![image](https://github.com/ianlucas/cs2-inventory-simulator/assets/32937653/ccd2bc48-41c8-4a0e-9589-e07573db878d)

However, even though the sticker is removed for all users on weapon skins, stickers can still be added.
![image](https://github.com/ianlucas/cs2-inventory-simulator/assets/32937653/23885949-b153-418d-a2ef-4d51cdeaf8bc)

It would be interesting if the sticker rule doesn't even show on the skins. It would be the same if I apply rules for nametag, stattrak, seed and wear, if I add them it doesn't show the options even in the skins.

**Comment by crashzk** [comment]
@ianlucas In theory it worked for new crafts, however I will edit a craft that I already have in the inventory and I can still add/remove stickers.

![image](https://github.com/ianlucas/cs2-inventory-simulator/assets/32937653/4e36b8ef-be43-4273-bbbd-bc68a959321a)

![image](https://github.com/ianlucas/cs2-inventory-simulator/assets/32937653/180b599d-8b81-4e0e-98ff-e69a3febbd8d)

Or now just update the Rules based on the new ones you added?

**Comment by ianlucas** [comment]
Yes, for editing items is another set of rules.
