### ISSUE TITLE
[BUG] GroupRole - Application Error

### ISSUE THREAD

**Issue by crashzk** [ianlucas/cs2-inventory-simulator#53]
I configured everything apparently correctly.

![image](https://github.com/ianlucas/cs2-inventory-simulator/assets/32937653/447a62bf-1483-4b59-a4d8-889cc87b3dcf)

![image](https://github.com/ianlucas/cs2-inventory-simulator/assets/32937653/c6d834a4-19ea-4370-a187-602a4b31e9bf)

![image](https://github.com/ianlucas/cs2-inventory-simulator/assets/32937653/31b59f80-05c8-4f2c-9589-397ef22465b1)

However, I receive this error on the server console and the website displays the error `Application Error`.
```
TypeError: Cannot read properties of undefined (reading 'value')
    at getUserGroupRuleOverwrite (file:///app/build/server/index.js?t=1712450849732.1455:114:49)
    at getRule (file:///app/build/server/index.js?t=1712450849732.1455:119:57)
    at file:///app/build/server/index.js?t=1712450849732.1455:149:9
    at async Promise.all (index 0)
    at getRules (file:///app/build/server/index.js?t=1712450849732.1455:146:5)
    at loader$f (file:///app/build/server/index.js?t=1712450849732.1455:5857:10)
    at Object.callRouteLoaderRR (/app/node_modules/@remix-run/server-runtime/dist/data.js:52:16)
    at callLoaderOrAction (/app/node_modules/@remix-run/router/router.ts:4043:16)
    at async Promise.all (index 0)
    at loadRouteData (/app/node_modules/@remix-run/router/router.ts:3320:19)
[Error: Unexpected Server Error]
```
![image](https://github.com/ianlucas/cs2-inventory-simulator/assets/32937653/f4046845-9d9b-4250-a2d6-753580011ced)

**Comment by crashzk** [comment]
Site works again when I delete data from the `UserGroup` table

![image](https://github.com/ianlucas/cs2-inventory-simulator/assets/32937653/3070ce8e-9bcb-465c-ad10-3a99efe035b0)

**Comment by avcrope** [comment]
> Site works again when I delete data from the `UserGroup` table
> 
> ![image](https://private-user-images.githubusercontent.com/32937653/320250924-3070ce8e-9bcb-465c-ad10-3a99efe035b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NjQ3MjgsIm5iZiI6MTcxMjQ2NDQyOCwicGF0aCI6Ii8zMjkzNzY1My8zMjAyNTA5MjQtMzA3MGNlOGUtOWJjYi00NjVjLWFkMTAtM2E5OWVmZTAzNWIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDA0MzM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2ZTZhOGEwZTFiNjMyZjk1ZjUzNzZkNGQxZjEyZjE2NGQ4ZTlhOWM0NDAwYWRlNGYyOTNmMDc4ZDRiYjA3MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lnLXeqfGdb0022LJW_jWJ3vV_dBzobq1cNsrX0baH2w)

Random Quistion but here did you lern how to get his open source on a webiste working also why is there no cases or keys on your website?

**Comment by crashzk** [comment]
There are no cases due to the Rules feature that has been implemented, with them we can control whether users have access or not, to do this you need to run the site yourself on your domain.

 Regarding compiling the code, yes, I managed to make it work on my domain.
