### ISSUE TITLE
[REQ] Case Quick Open Feature

### ISSUE THREAD

**Issue by avcrope** [ianlucas/cs2-inventory-simulator#55]
When you open a case you can click escape or the close button and it shows the weapon you got right away like in game. To minimize time between cases.

**Comment by ianlucas** [comment]
This already can be done by refreshing the page.

**Comment by RandomCSGO** [comment]
I agree with this request, the F5 for fast opening is pretty laggy, i think a little "skip" button can be cool.

**Comment by ianlucas** [comment]
> I agree with this request, the F5 for fast opening is pretty laggy, i think a little "skip" button can be cool.

Open a new issue requesting it. I think in CS2 we skip by closing, right?

**Comment by avcrope** [comment]
> > I agree with this request, the F5 for fast opening is pretty laggy, i think a little "skip" button can be cool.
> 
> Open a new issue requesting it. I think in CS2 we skip by closing, right?

it skips by clicking F5 and then it has a popup saying what item yougot when you go back in your inventory
