### ISSUE TITLE
[REQ/RULE] Rules improvements

### ISSUE THREAD

**Issue by crashzk** [ianlucas/cs2-inventory-simulator#56]
I have the following rules configured:

![image](https://github.com/ianlucas/cs2-inventory-simulator/assets/32937653/ee65e9e6-86ac-4a56-9807-5981b9ea0a65)

The problem is that if I put the `weapon` rule in **CraftHideType**, the user can't even craft a skin, as you can see in the screenshot below:

![image](https://github.com/ianlucas/cs2-inventory-simulator/assets/32937653/f894b0d6-eef7-4993-bec7-7c156d0d3dc5)

Skins/Weapons do not show in this case.

The Sticker rule too, even though he is unable to craft new stickers, the ones he already has in his inventory he can apply and the stickers on weapons he can remove.

![image](https://github.com/ianlucas/cs2-inventory-simulator/assets/32937653/3908bcff-97a3-4f5b-87b9-e965f5bbe023)

![image](https://github.com/ianlucas/cs2-inventory-simulator/assets/32937653/8575a7f5-14e8-424b-aedf-713beb1509de)

![image](https://github.com/ianlucas/cs2-inventory-simulator/assets/32937653/d277235e-0180-4e1c-ab3f-16a3d838a906)

What I thought, if you put in the rules that the user will not be able to edit/create stickers, make visible to them what they already have but without the option to apply/remove stickers.

Same thing for Graffiti, Patches, Pins and Music Kit, all items in this case.

**Comment by ianlucas** [comment]
Just for clarification, we are dealing with three different areas:

1. `Craft*` rules are related to adding items to the inventory.
2. `Edit*` rules are related to editing inventory items (& showing "Edit" option in inventory item context menu).
3. `InventoryItemAllow*` rules are related to showing options in inventory item context menu.
