### ISSUE TITLE
[REQ] Preview Images for Weapon/Knife/Glove Seed+Wear+StatTrak and Sticker Wear

### ISSUE THREAD

**Issue by crashzk** [ianlucas/cs2-inventory-simulator#6]
Some skins, for example, Case Hardened have different seeds, blue on the weapon changes position and so on. However, changing this seed in the web interface does not change anything on the website. It would be possible to implement this feature since in the option to view the wear it already exists on the website.

![image](https://github.com/ianlucas/cs2-inventory-simulator/assets/32937653/00f95045-0c01-4e07-807d-b64eb28863cb)

Same thing for Knives and Gloves.

**Comment by ianlucas** [comment]
Unfortunately this is not easy to achieve just by using the assets from the game. Each weapon/glove/knife paint has three generated images: three wears (heavy, medium, light) of a fixed seed (probably 1) -- that's what we're using in the app (btw it's probably an incorrect visualization and we still need to know the wear each image represents).

So AFAIK this requires hacking into the game and extracting a fair amount of images for each weapon/glove/knife to have a proper visualization of wear and seed. I would appreciate any help on this.

For anyone interested, here's how the application is [resolving the item image](https://github.com/ianlucas/cslib/blob/d22d66c81970664c4a4481393a34827bc079cca2/src/economy.ts#L348-L372):

| Condition | Image |
| ----------- | ------- |
| no wear OR wear < 1 / 3 | light |
| wear < 2 / 3 | medium |
| wear < 1 | heavy |

**Comment by ianlucas** [comment]
It's very unlikely someone is going to look into this for free, so I'll close this issue. In the future we may try to find ways to provide this.

**Comment by crashzk** [comment]
Ok, I'll also keep an eye on websites, etc., to find something informative here.

**Comment by crashzk** [comment]
Leaving it on record for the future.

I found some sites that somehow displayed these skins with different seeds.

https://buff.163.com/market/csgo#game=csgo&page_num=1&search=Case&tab=top-bookmarked
https://dashskins.gg/
