### ISSUE TITLE
[REQ] Improvements to `UserGroup` & `UserRule` tables

### ISSUE THREAD

**Issue by crashzk** [ianlucas/cs2-inventory-simulator#60]
Both tables only record the user ID, would it be possible to have a column to automatically search for the Name of the user ID just for easier identification?

This name would be automatically taken based on the User table column name, and placed in the `UserGroup` & `UserRule` tables when we register someone in them.

**Comment by ianlucas** [comment]
User ID is the only source of truth for user identification, name and other columns can be pretty much the same for other users. Ideally some other app should be managing the users using those tables.
