### ISSUE TITLE
[REQ/RULE] Inventory Item Equip

### ISSUE THREAD

**Issue by crashzk** [ianlucas/cs2-inventory-simulator#64]
Would it be possible to create rules for equipping and unequipping items? In theory, it would be for all items, graffiti, agents, gloves, skins, knives, pins, etc., all items, but each one has its own rules.

For example, if you want to remove the option to equip graffiti that the user already has in their inventory, you can configure the rule, the same thing for Music Kit and other items.

**Comment by ianlucas** [comment]
Not sure why you'd want this, but what if the user had the item equipped and you added a rule to prevent the user from unequipping it? It's not feasible to go through all the users that have the item equipped and unequip it, so it'd be stuck until it's enabled back.

I think it makes more sense to apply this restriction in the Equipped API, so that it won't return the item if it's blocked by a rule.

**Comment by crashzk** [comment]
Really, I don't think unequipping makes much sense, just a rule for equipping would be fine.

So, even if the user no longer has access to equip that item, they can still unequip it, they just won't be able to equip it anymore until they have access to the item again.

**Comment by ianlucas** [comment]
Okay, so for the scenario where the user has an item equipped and it's blocked, it will remain equipped and the API will return it as equipped, right?

**Comment by crashzk** [comment]
This, even if he no longer has access to equip the item, if it is already equipped it remains equipped, only if it is removed he will no longer be able to equip it until it is lit again.

Only if you find some way to remove the item from the user that they no longer have access to, a viable way in this case.

**Comment by ianlucas** [comment]
Item won't be returned by Equipped API when Equip is hidden for the user. If the item was equipped before the enforcement of the rule, it will remain equipped in the database, but the UI and Equipped API will see it as not equipped.

**Comment by crashzk** [comment]
Perfect, thanks. Just an observation, documentation has not been updated, I don't know if I intend to inform this new rule in it as well.
