### ISSUE TITLE
[BUG] Application Error with no message

### ISSUE THREAD

**Issue by Kroytz** [ianlucas/cs2-inventory-simulator#66]
Steps:
- log out
- login again
- see the page Application Error with lightred color box with no message below

**Comment by ianlucas** [comment]
I'm unable to replicate it, can you give me your Steam ID?

**Comment by ianlucas** [comment]
Okay, I think I found it, working on it.

**Comment by Kroytz** [comment]
My steam64 is 76561197967281863.
but not only me get the error after login for these days (I'm using your plugin on my ten-man match server and players found they start get error about 2 weeks ago)

**Comment by ianlucas** [comment]
I see, I'll take a look at the logs, lot really monitoring this. I've deployed the fix, let me know if it worked.

**Comment by Kroytz** [comment]
Already works for me, tested by switch my Language setting to SChinese. Thank you!
