### ISSUE TITLE
[REQ] Craft More Than One Weapon Or Knife

### ISSUE THREAD

**Issue by avcrope** [ianlucas/cs2-inventory-simulator#67]
i think it would be nice if you can have the option to craft multiple knifes or guns. maybe and option to have all the weapons or knifes random wear, float, or pattern but that really doesn't matter because you can change it in the edit menu anyway but still be cool.

**Comment by ianlucas** [comment]
The idea of crafting is to compose a unique weapon. Stickers, cases, etc. have quantity because they don't have attributes. And you already can have random weapons by opening cases, so this feature really does not make sense right now.

**Comment by avcrope** [comment]
> The idea of crafting is to compose a unique weapon. Stickers, cases, etc. have quantity because they don't have attributes. And you already can have random weapons by opening cases, so this feature really does not make sense right now.

I understand thankyou tho
