### ISSUE TITLE
[REQ] Option to wear stickers

### ISSUE THREAD

**Issue by crashzk** [ianlucas/cs2-inventory-simulator#7]
Would it be possible to implement some way of managing the sticker that we place on the weapon?

![image](https://github.com/ianlucas/cs2-inventory-simulator/assets/32937653/5d71ae35-32ee-4298-8402-f51cffa27199)

**Comment by ianlucas** [comment]
36acdc8f1d05487b4566bb03f495756a6bf8aa3e implemented sticker wear changes by right clicking the item > Scrape Sticker. I'm planning to add a quick setting in the sticker editor as well.
