### ISSUE TITLE
[BUG] Icons with glitchy sizes

### ISSUE THREAD

**Issue by crashzk** [ianlucas/cs2-inventory-simulator#70]
I currently use it on Google Chrome and I haven't noticed any bugs visually, even through the Steam browser.

However, users reported this visual bug using Opera GX.

![image](https://github.com/ianlucas/cs2-inventory-simulator/assets/32937653/7f0d652d-ce02-4b0a-bc04-6112dac12b29)

As you can see, the research magnifying glass is huge. 😄 

![image](https://github.com/ianlucas/cs2-inventory-simulator/assets/32937653/821203ff-5edf-4b43-ae73-372da9d31610)

**Comment by ianlucas** [comment]
LOL, personally I use Microsoft Edge, but I suspect this being caused by an extension, anyway this happens because these icons don't have a defined height and something is causing an error in the users' browser. This will be patched by tomorrow.
