### ISSUE TITLE
[REQ] Add system translations for all supported languages

### ISSUE THREAD

**Issue by crashzk** [ianlucas/cs2-inventory-simulator#72]
I noticed that changing the site's language to something other than `pt-BR` and `en` changes the names of the skins/items.

However, the website menu, not the interface, remains in English.

![image](https://github.com/ianlucas/cs2-inventory-simulator/assets/32937653/c5b67f7b-8327-4a03-8c23-22224a8c5581)

![image](https://github.com/ianlucas/cs2-inventory-simulator/assets/32937653/e0fce500-2e81-4586-832a-65c1205c4577)

Wouldn't it be interesting to implement the full translation into the language? If so, how can we help with new translations.

ChatGPT can be a great help for this, so we will have a base for new languages ​​and then let it be verified by users who are native to the language.

**Comment by ianlucas** [comment]
I've added the files for the supported languages in the app, but I won't translate from English as I think AI is not reliable enough for this job (and it contains a lot Counter-Strike terms).

In the future if the website/project gains more broad access I may do that, but for now all non-English languages (excluding Brazilian Portuguese which I provide) will fallback to English.

**Comment by crashzk** [comment]
@ianlucas 

Note: I believe a website would be interesting to help with translations in the future.

https://crowdin.com/

Something like this would be possible, so we can get easier help with translating into several languages.
