### ISSUE TITLE
[REQ] Import / Export Craft

### ISSUE THREAD

**Issue by ezz3r** [ianlucas/cs2-inventory-simulator#75]
Would be cool if you could export an Skin that you crafted so your friend can import it.

**Comment by crashzk** [comment]
I believe it could be a complicated idea of ​​this suggestion: https://github.com/ianlucas/cs2-inventory-simulator/issues/25

It would be the same thing I believe, loadout system, etc.

**Comment by ianlucas** [comment]
I think it's a good ideia. Just for my future reference:

Inventory Item > Share (context menu)
Inventory Item > Inspect (screen) > Share icon
Inventory Item > Edit (modal) > Share icon
Craft > Import...

**Comment by ianlucas** [comment]
Actual implementation:

Inventory Item > Share (context menu)
Inventory Item > Inspect (screen) > Share icon

Shared item can be added to the user's inventory if they can (rules are taken in consideration).
