### ISSUE TITLE
[REQ] Improve Text Sliding Effect

### ISSUE THREAD

**Issue by crashzk** [ianlucas/cs2-inventory-simulator#78]
![image](https://github.com/ianlucas/cs2-inventory-simulator/assets/32937653/a0b6f9c1-1aa9-4a08-adcc-11b6f5d7c763)

As you can see in the printout, the `Nametag` option, translated into Portuguese-BR, becomes `Etiqueta de Nome`, but it doesn't show the entire sentence, so to speak, it keeps moving from one side to the other so that we can somehow visualize it.

It would be possible to increase the craft option a little and thus improve the visualization for the Portuguese-BR language, I believe it is greater than the Brazilian translation.

**Comment by ianlucas** [comment]
Unfortunately we can be adjusting the panel for every language, so eventually one language will have a larger string that can be shown on screen, but I see some improvements I can make on the sliding effect to make it a bit more pleasant.
