### ISSUE TITLE
after installing on localmacine , can't change ulr's

### ISSUE THREAD

**Issue by normadelic** [ianlucas/cs2-inventory-simulator#79]
![Ekrano kopija 2024-05-29 074026](https://github.com/ianlucas/cs2-inventory-simulator/assets/167678649/d0163ed3-6fbd-4951-9a05-c923f7dc96e6)
Where need to change it ? i spend 2 days for look in for it :D

**Comment by ianlucas** [comment]
https://github.com/ianlucas/cs2-inventory-simulator/blob/main/docs/rules.md
