### ISSUE TITLE
[REQ] API for Giving Cases to a User

### ISSUE THREAD

**Issue by RandomCSGO** [ianlucas/cs2-inventory-simulator#87]
Add a rule which allows one or more cases to be given randomly (and to be able to change the items which can be dropped via the rules) such as for example for CSGO at the end of the game with cases drops but allowing more options (perhaps to deactivate basic in the rules?) like item drops (or cases/items defined in the rules) for MVPs, eliminations (or for example every 5 kills etc.).

Basically taking the box drop system that CSGO had at the end of a game (and with a few more options for those who want more customization) because I don't see the weekly drop system of CS2 currently being interesting for the plugin but I think adding more interaction with the game servers could be more interesting.

**Comment by crashzk** [comment]
Interesting request. I believe we can include total control of these resources in it.

Offer a drop system for cases, capsules, stickers, sprays and skins. Just like her old self in CSGO.

However, it would be interesting to believe that the drop system is realistic, rare items, very rare, drop have a drop limit for the player's SteamID.

Antiques in CSGO only dropped twice per season/month. As far as I remember.

**Comment by ianlucas** [comment]
> Interesting request. I believe we can include total control of these resources in it.
> 
> Offer a drop system for cases, capsules, stickers, sprays and skins. Just like her old self in CSGO.
> 
> However, it would be interesting to believe that the drop system is realistic, rare items, very rare, drop have a drop limit for the player's SteamID.
> 
> Antiques in CSGO only dropped twice per season/month. As far as I remember.

The development for this issue will be pretty basic, it'll be two APIs, one for adding items to a user inventory and other for giving a case with some parameters (caseid, souvenir, map, etc) - so it will be up to the plugin to handle the logic for deciding which item to give (using the first API) or simply calling the second to get a random case.

A more advanced logic for giving items must be dealt in another issue when this one is resolved.
