### ISSUE TITLE
[REQ] Option to apply sticker to the weapon

### ISSUE THREAD

**Issue by crashzk** [ianlucas/cs2-inventory-simulator#9]
Would it be possible to implement an option to apply the sticker we crafted to a weapon without stickers?

![image](https://github.com/ianlucas/cs2-inventory-simulator/assets/32937653/94d05ab4-cb13-4120-8c42-f25cd1baea58)

**Comment by crashzk** [comment]
Just an observation, I still can't apply stickers that would already be in the inventory.

![image](https://github.com/ianlucas/cs2-inventory-simulator/assets/32937653/64b753ad-16d7-4abc-a040-b9fce3fb6b02)

**Comment by ianlucas** [comment]
> Just an observation, I still can't apply stickers that would already be in the inventory.
> 
> ![image](https://private-user-images.githubusercontent.com/32937653/292059994-64b753ad-16d7-4abc-a040-b9fce3fb6b02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMjczMTAsIm5iZiI6MTcwMzEyNzAxMCwicGF0aCI6Ii8zMjkzNzY1My8yOTIwNTk5OTQtNjRiNzUzYWQtMTZkNy00YWJjLWEwNDAtYjlmY2UzZmI2YjAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDAyNTAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlOGY0ZGM2YjIwZjUxNzkxZjg3MjM2OTZkMDcxMWFmNTFiYWY5YjI0ZDJmMTFkNWMyN2VmOGU4YTAzMzU1ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QAfAg71h_KRBIzeS-oFmzm0LGaKowr_npkpum3UOntA)

The code is still not deployed to the website. It will be shortly.
